# Generated by Django 5.1.5 on 2025-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField(auto_now=True)),
                ('is_payed', models.BooleanField(blank=True, default=None, null=True)),
                ('payment_form', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
