# Generated by Django 5.1.5 on 2025-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_is_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_payed',
            field=models.CharField(blank=True, choices=[('Pago', 'Pago'), ('A pagar', 'A Pagar')], max_length=7, null=True),
        ),
    ]
