# Generated by Django 5.1.5 on 2025-02-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
