# Generated by Django 5.1.5 on 2025-02-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='imagem',
        ),
    ]
